ProfessionalWiki/chameleon

docs/customization.md

Hi Stephan,
I started my work on the docu.
First I brought a new structure to it - I hope it's clearer than before. 
It seems Github doesn't mark the elements I (just) moved.
Looking forward to your feedback. More docu to follow soon :)

Reordered elements, added some text and addCacheTriggerFile

---

docs/components.md
src/Components/NavbarHorizontal/PageTools.php
src/Components/NavbarHorizontal/PageToolsAdaptable.php
tests/phpunit/Fixture/NavbarHorizontal/PageToolsAdaptable.xml
tests/phpunit/Unit/Components/NavbarHorizontral/PageToolsAdaptableTest.php

I understand and agree that the maintainer of the Chameleon skin shall have the
irrevocable and perpetual right to make and distribute copies of any
contribution, as well as to create and distribute collective works of any
contribution, under the current license or under any other open source license
chosen by the maintainer.

closes #59 (add an adaptable NavbarHorizontal/PageTools Component)

---

Chameleon.php
composer.json

* Update composer.json
* Update Chameleon.php

Update license identifier to match SPDX v3.1

---

resources/styles/screen.less

Prevent chrome scrolling behaviour

---

docs/index.md

Yes it is derp it does not work without the newline...

Fix markdown links

---

tests/phpunit/Unit/Components/ComponentTest.php

This makes it compatible with PHPUnit 8 which MediaWiki will
shortly migrate to: https://phabricator.wikimedia.org/T234597

Use expectException() instead of @expectedException

---

docs/customization.md

Simple grammar fix and tone change.

Grammar Fix customisation.md

---

tests/phpunit/Unit/Components/Modifications/ShowOnlyForTest.php

Make class name psr-4 compliant

---

resources/styles/Components/NavbarHorizontal.scss

Wasn't too sure about SCSS, so feel free to give pointers if necessary. Also probably needs more testing than just my very specific case, just to be sure.

Fix #106 by making sure icons adhere to the text color used in the navbar

---

composer.json
skin.json

This allows installation without composer.

switched to MediaWiki autoloading

---

resources/i18n/en.json

Provide a description

---

skin.json

Set namemsg to use skinname-chameleon
From https://phabricator.wikimedia.org/T252463#6156277

Lowercase canonical name in skin.json

---

src/Components/NavMenu.php

See discussion at https://phabricator.wikimedia.org/T253322#6162186.

addressed remaining phan error

---

resources/styles/_mediawiki.legacy.shared.scss

Reinstate indentation using colons

---

src/Components/NavbarHorizontal/Toolbox.php

Fix for #225

---

src/Components/SearchBar.php
tests/phpunit/Unit/Components/SearchBarTest.php

Issue 150 with unit tests

---

layouts/clean.xml
layouts/fixedhead.xml
layouts/navhead.xml
layouts/standard.xml
layouts/stickyhead.xml

Bump all layouts to the latest schema and fix one old URL

Update layout xml-model

---

docs/release-notes.md
resources/styles/_extensionfixes.scss

Fixes: #178 
Addresses:
* clipping
* jumping around
* minor mobile improvements

Improve MultimediaViewer support

---

src/Chameleon.php

I don't have a WAMP setup to test with, but this should short circuit the logic that causes the issue in #81 and #249

Add directory separator short circuit

---

README.md
composer.json
docs/migration.md

Update IRC URL

---

docs/components.md
layouts/clean.xml
layouts/fixedhead.xml
layouts/layout.rng
layouts/navhead.xml
layouts/standard.xml
layouts/stickyhead.xml
maintenance/validateLayout.php
src/Components/Cell.php
src/Components/Container.php
tests/phpunit/Fixture/Cell.xml
tests/phpunit/Unit/Components/CellTest.php

Add id to containers, update documentation

---

docs/components.md
layouts/clean.xml
layouts/fixedhead.xml
layouts/layout.rng
layouts/navhead.xml
layouts/standard.xml
layouts/stickyhead.xml
maintenance/validateLayout.php
src/Components/Cell.php
src/Components/Container.php
tests/phpunit/Fixture/Cell.xml
tests/phpunit/Unit/Components/CellTest.php

Backport structure component id support

---

docs/components.md
docs/release-notes.md
layouts/layout.rng
resources/i18n/en.json
resources/i18n/es.json
resources/i18n/qqq.json
resources/styles/Components/NavbarHorizontal.scss
src/Components/NavbarHorizontal.php

Add navbar toggler text support

---

resources/styles/_variables.scss
resources/styles/themes/_light.scss

Fixes: #288
Fixes: https://github.com/scssphp/scssphp/issues/476

Convert percent to float

---

src/Components/NavbarHorizontal/PersonalTools.php
tests/phpunit/Unit/Components/NavbarHorizontal/PersonalToolsTest.php
tests/phpunit/Util/MockupFactory.php

Replace isLoggedIn()

---

.github/workflows/ci.yml
composer.json
docs/installation.md
docs/release-notes.md
skin.json
src/Hooks/SetupAfterCache.php
tests/phpunit/Unit/Components/ComponentTest.php
tests/phpunit/Unit/Components/NavbarHorizontalTest.php
tests/phpunit/Unit/Hooks/SetupAfterCacheTest.php

Fixes https://github.com/ProfessionalWiki/chameleon/issues/309

Add PHP 8.1 compat

---

src/Chameleon.php

Add missing namespace workaround

---

docs/components.md
layouts/clean.xml
layouts/fixedhead.xml
layouts/layout.rng
layouts/navhead.xml
layouts/standard.xml
layouts/stickyhead.xml
resources/styles/Components/MainContent.scss
src/Components/AggregateComponentTrait.php
src/Components/ContentBody.php
src/Components/ContentHeader.php
src/Components/Indicators.php
src/Components/MainContent.php
tests/phpunit/Fixture/ContentBody.xml
tests/phpunit/Fixture/ContentHeader.xml
tests/phpunit/Fixture/Indicators.xml
tests/phpunit/Unit/Components/ContentBodyTest.php
tests/phpunit/Unit/Components/ContentHeaderTest.php
tests/phpunit/Unit/Components/IndicatorsTest.php
tests/phpunit/Unit/Components/MainContentTest.php

Extract components from main content

---

src/Components/NavbarHorizontal/PersonalTools.php
tests/phpunit/Unit/Components/NavbarHorizontal/PersonalToolsTest.php
tests/phpunit/Util/MockupFactory.php

Add showUserName tests

---

.github/workflows/ci.yml

And drop PHP 7.4 on MW master.

Add MW 1.39 to CI

---

docs/release-notes.md
skin.json
src/Chameleon.php
src/Hooks/ResourceLoaderRegisterModules.php
src/Hooks/SetupAfterCache.php
tests/phpunit/Unit/Hooks/ResourceLoaderRegisterModulesTest.php

Create hook class and handle deprecated external link icons

---

docs/release-notes.md
src/Hooks/ResourceLoaderRegisterModules.php
tests/phpunit/Unit/Hooks/ResourceLoaderRegisterModulesTest.php

Replace 'legacy' and 'content' features

---

docs/installation.md

Allow selecting the two commands individually

Format installation.md

---

resources/styles/Components/Toc.scss

Fixes https://github.com/ProfessionalWiki/chameleon/issues/408
From https://github.com/ProfessionalWiki/chameleon/pull/405. Thanks @DanielWTQ.

Fix ToC hide/show button

---

src/Components/NavbarHorizontal/PersonalTools.php

Minor code cleanup

---

resources/styles/_mediawiki.legacy.shared.scss

Note: to be merged after core change https://gerrit.wikimedia.org/r/c/mediawiki/core/+/712747

Remove old CSS class for file deletion

---

docs/components.md
docs/release-notes.md
layouts/clean.xml
layouts/fixedhead.xml
layouts/layout.rng
layouts/navhead.xml
layouts/standard.xml
layouts/stickyhead.xml
maintenance/validateLayout.php
src/Components/NavbarHorizontal/PersonalTools.php

Follow up to https://github.com/ProfessionalWiki/chameleon/pull/400/files#r1695896096
FYI @thomas-topway-it @krabina

Add showUserAvatar parameter

---

resources/js/Components/toc.js
resources/styles/Components/Toc.scss

Fix scrollspy offset in MW 1.39

---

resources/styles/Components/Toc.scss
src/Components/Toc.php

Add a body class when the TOC component is used

---

src/Menu/MenuFromLines.php

For failing CI on MW master: https://github.com/ProfessionalWiki/chameleon/actions/runs/11253110995/job/31287681900

Remove wfUrlProtocols
