- composer.json
- package.json
`npm run build:docs` is automatically invoked on `composer build`.
It will add TOCs to all markdown files containing a section like
```
```
> Add npm build:docs script

- docs/components.md
- docs/release-notes.md
- layouts/layout.rng
- layouts/standard.xml
- maintenance/validateLayout.php
- src/Components/MainContent.php
- src/Components/PersonalTools.php
The attribute was introduced to keep backwards compatibility. If the
PersonalTools component is used, it is recommended to always set this attribute
to yes and use an independent NewtalkNotifier component.
The standard layout uses this now.
hideNewtalkNotifier:
* Already deprecated.
* Allowed values: Boolean (yes|no)
* Default: no
* Optional.
If set the newtalk notifier will not be shown.
This attribute has no effect when used inside the NavbarHorizontal component.
Also: Fix validateLayout.php to work from any directory.
> PersonalTools: Add attribute hideNewtalkNotifier + use it for Standard layout

- docs/release-notes.md
- src/Components/NavbarHorizontal.php
In case an unknown component is encountered in its XML layout description,
NavbarHorizontal tries to find and use a component class in the
Skins\Chameleon\Components\Component namespace to format the component.
> NavbarHorizontal: Allow custom types and classes for Navbar elements

- resources/styles/screen.less
Just two (minor) fixes where MediaWiki's native styles (mw-headline and mw-body) seem to interfere with Bootstrap styles.
> D groenewegen patch 1

- docs/components.md
- layouts/layout.rng
- src/Components/NavbarHorizontal/SearchBar.php
- src/Components/SearchBar.php
* Allowed values: String (`search`|`go`|`search go`)
* Default: `search go`
* Optional.
Fixes #18
> Allow 'buttons` attribute for Searchbar component description

- src/SkinChameleon.php
Allows skins that build on top of Chameleon to set a specific layout file
without the need to manipulate the global config variables.
> Added a template method for subclasses

- docs/legal.md
MediaWiki is licensed as GPL v2 or later, so including any GPL v3 projects
is totally OK, since you're just using it under the terms of v3. And since
MediaWiki depends on and bundles Apache 2.0 projects (which is only
compatible with GPL v3), MediaWiki itself is effectively GPL v3. So there's
no problem with bundling GPL v3 projects with MediaWiki, and in fact the
1.31 release will contain GPL v3 or later code in the tarball.
> legal: Remove misleading/incorrect text about bundling

- build/travis/build.sh
- composer.json
- docs/installation.md
- skin.json
- src/Chameleon.php
This completes the changes that allow Chameleon to be installed without composer.
- Remove the mediawiki/mediawiki, mediawiki/mw-extension-registry-helper, and mediawiki/bootstrap composer packages
- Remove mw-extension-registry-helper code
- Add Bootstrap as a requirement to skin.json
- Bumps Chameleon version to 3.0.0
- Requires a 4.2 release of Bootstrap
- Requires Bootstrap to be enabled manually (e.g. `wfLoadExtension( 'Bootstrap');` in LocalSettings.php)
fixes https://github.com/ProfessionalWiki/chameleon/issues/120
> Composer: rm mediawiki, mw-extension-registry-helper, bootstrap

- src/Chameleon.php
Fixes https://github.com/ProfessionalWiki/chameleon/issues/147
> Make 'mediawiki.ui.button' unconditionally loaded

- .phan/config.php
It's currently incorrect when MW_INSTALL_PATH === false
Results in
```
00:09:09 WARNING: Caught exception while listing files in '/mediawiki/skins/chameleon/.phan/../..//extensions/Bootstrap': RecursiveDirectoryIterator::__construct(/mediawiki/skins/chameleon/.phan/../..//extensions/Bootstrap): failed to open dir: No such file or directory
```
> Fix defining $IP in .phan/config.php

- src/Chameleon.php
SkinTemplateOutputPageBeforeExec is deprecated but BlueSpice uses this
hook to communicate with Chameleon skin. A new hook is provided to allow
this integrate to continue with minimal disruption
Fixes: #167
> Provide a Chameleon specific version of SkinTemplateOutputPageBeforeExec

- src/ChameleonTemplate.php
The parent method will soon be removed. OutputPageBodyAttributes hook is now the  only supported way of adding stuff to the body tag. Note the hook is not new.
> Do not advise using addToBodyAttributes() method

- docs/components.md
In the message menu items have to be separated by [comma](https://github.com/ProfessionalWiki/chameleon/blob/654619e742e571393c73c711e3435c046c31251a/src/Components/NavMenu.php#L202)
> Added hint for message separation

- src/Components/NavbarHorizontal/Toolbox.php
Add support for > 1.35 as well as retaining the existing support
for < 1.35
Fixes: #214
> Use of BaseTemplate::getToolbox was deprecated in MediaWiki 1.35

- src/Components/NavMenu.php
e.g.
```
$wgHooks['SidebarBeforeOutput'][] = function ( $skin, &$bar ) {
text.
$bar[ 'sunday' ] = [
[
'label' => 'msg-myid',
'msg' => 'my-label-message',
'href' => '//example.com'
]
];
};
```
Fixes: #212
> `id` may not be defined so check

- skin.json
- src/Chameleon.php
- src/Hooks/SetupAfterCache.php
(disclaimer: untested - couldn't get this working locally)
This module is no longer added to skins so you shouldn't need to remove this module provided you bump the mediawiki dependency
Fixes: #110
> No need to remove legacy module in 1.35

- resources/js/Components/Modifications/sticky.js
Refs: #139
Fixes: #139 
When the page is loaded with a URI fragment the sticky needs to be refreshed to recalculate its position.
Tested with:
* MediaWiki 1.35.2
* Chameleon (master branch)
* Chameleon layout: stickyhead
* Browsers:
* Firefox 88
* Chromium 90
When a URL containing a fragment (e.g. `/wiki/Special:Version?uselayout=stickyhead#mw-version-ext`) is opened directly in the address bar, then the sticky will now be repositioned without requiring manual scrolling.
> Add sticky refresh on page load with fragment

- src/Components/NavbarHorizontal/Toolbox.php
@JeroenDeDauw This fixes the failing unit test in the Toolbox component after the merge of my PR:
https://github.com/ProfessionalWiki/chameleon/runs/2534352988
I suppose having an unchecked array key access here wasn't safe in the first place.
Local unit test result with:
* PHP 7.4
* MediaWiki 1.35.2
* Chameleon: master branch
> Fix empty toolbox in unit tests

- src/Components/NavMenu.php
- tests/phpunit/Unit/Components/GenericComponentTestCase.php
- tests/phpunit/Unit/Components/NavMenuTest.php
Fixes: #181 
This is the new HTML with a valid id and class:
```html
<div class="nav-item dropdown">
<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" data-boundary="viewport">A long question?</a>
<div class="dropdown-menu p-A-long-question.3F" id="p-A-long-question.3F">
<div id="n-An-exclamation.21"><a href="/wiki/An_exclamation!" class="nav-link n-An-exclamation.21">An exclamation!</a></div>
</div>
</div>
```
Not too sure about this unit test, though. Does the mocking here skip too many MW steps? I'm just checking when I get the (mocked) sidebar data as it is currently returned then it will return the better id. However, it does not rely on MW actually generating the current invalid id during test runtime.
> Add NavMenu id fix

- resources/js/Components/Modifications/sticky.js
- Fixes a problem with scrolling to mediawiki h2 headers and anchors containing a `.` (dot) symbol in their `id` attribute
- Fixes a problem with scroll function not calculating sticky navbar height properly due to `hcSticky.refresh` happening after the scroll fix run
> Fixes anchor links scroll issue with sticky navbar

- docs/customization.md
- docs/release-notes.md
- skin.json
- src/Hooks/SetupAfterCache.php
Fixes: #183 
Added new LocalSettings variable: `egChameleonEnableExternalLinkIcons`.
The default behaviour is to not show the icons in order to maintain backward compatibility.
When the variable is set to true it will load the MediaWiki external links styling: https://github.com/wikimedia/mediawiki/blob/master/resources/src/mediawiki.skinning/content.externallinks.less
> Add external link icons support

- schema/1.0/layout.rng
- schema/1.1/layout.rng
- schema/1.2/layout.rng
- schema/3.0/layout.rng
The layout validation fails and it seems like it is because the remote schema (on GitHub pages) still references the old URL.
```
root@f4506d3d0e38:/var/www/html/skins/chameleon# php maintenance/validateLayout.php layouts/standard.xml 
layouts/standard.xml: 
Error 17: Element structure has wrong namespace: expecting https://cmln.github.io/chameleon/schema/3.0/layout.rng in /var/www/html/skins/chameleon/layouts/standard.xml on line 26
```
> Update GitHub pages schema ns

- docs/release-notes.md
- docs/variables.md
- resources/styles/Components/NavbarHorizontal.scss
- resources/styles/_variables.scss
Fixes: #221 
```php
$egChameleonExternalStyleVariables = [
'cmln-grid-breakpoints' => '(xs: 0, sm: 576px, md: 768px, lg: 992px, cmln: 1234px, xl: 1900px)'
];
```
```php
$egChameleonExternalStyleVariables = [
'cmln-navbar-horizontal-collapse-point' => 'lg',
'cmln-grid-breakpoints' => '(xs: 0, sm: 500px, md: 800px, lg: 1000px, xl: 1900px)'
];
```
```php
$egChameleonExternalStyleVariables = [
'cmln-navbar-horizontal-collapse-point' => 'medium',
'cmln-grid-breakpoints' => '(nothing: 0, small: 123px, medium: 456px, large: 789px, extra-large: 2000px)'
];
```
(This is not necessarily sufficient as there are other Bootstrap variables that might need to be adjusted to accommodate such an extreme change.)
> Allow breakpoint overrides

- docs/customization.md
- docs/release-notes.md
- resources/styles/_variables.scss
- resources/styles/themes/_empty.scss
- skin.json
- src/Chameleon.php
- src/Hooks/SetupAfterCache.php
- tests/phpunit/Unit/ChameleonTemplateTest.php
- tests/phpunit/Unit/Hooks/SetupAfterCacheTest.php
I'm not sure if the original intent behind theme support was to have out-of-the-box named themes like "light" and "dark" (or like Bootswatch), or whether it was meant to allow the administrator to more explicitly replace the `_light` theme in a dedicated theme variable as opposed to the more generic `$egChameleonExternalStyleModules`. This PR takes the former approach with a new variable `$egChameleonThemeFile`.
I want a quick way to remove most/all of Chameleon's default styles (i.e. by simply not loading the default theme) and at the moment at least 2 issues are caused by the `_light` theme overriding a `!default` variable which prevents it from being overridden in `LocalSettings.php`.
#182 - `link-color`: https://github.com/ProfessionalWiki/chameleon/blob/master/resources/styles/themes/ …
> Add initial theme support

- src/Components/NavbarHorizontal/LangLinks.php
I have been a bit too enthusiastic in #194
.$linkItem['id'] is not needed in Components/NavbarHorizontal/LangLinks.php and gives an error message 
"Notice
: Undefined index: id in
......../skins/chameleon/src/Components/NavbarHorizontal/LangLinks.php
on line 91
> fix LangLinks.php .$linkItem['id'] error

- .github/workflows/ci.yml
- composer.json
- docs/installation.md
- docs/release-notes.md
- skin.json
- src/Chameleon.php
- src/Components/NavbarHorizontal/Toolbox.php
- src/Components/PageTools.php
- src/Components/SearchBar.php
- tests/phpunit/Unit/Components/ComponentTest.php
- tests/phpunit/Unit/Components/MainContentTest.php
Fixes: #246 
This raises the minimum versions and removes all the explicit workarounds.
I used MW 1.35's official PHP 7.3.19 requirement. Should we stick to that, or just raise it to 7.4 as part of Chameleon 4.0.0?
PHP 7.3's active support ended Dec 2020 and security support ends Dec 2021. If we go with the latter it means Chameleon is technically not supported everywhere MW 1.35 is. If we don't do this now, I assume it will be another major version change later?
There shouldn't currently be any PHP 7.4-only code anywhere, because CI unit tests still worked with 7.1.
> Raise minimum: MW 1.35

- docs/release-notes.md
- src/Chameleon.php
Fixes: #267 
* Fixes the MW 1.31 regression introduced by https://github.com/ProfessionalWiki/chameleon/commit/40a60c9aaa9b1afc38a4dc88dbdd2bec6f232f58
* Replace the deprecated `setupSkinUserCss` with `initPage`
Not sure if MW 1.32 - 1.34 worked correctly with https://github.com/ProfessionalWiki/chameleon/commit/40a60c9aaa9b1afc38a4dc88dbdd2bec6f232f58 (i.e. Chameleon 3.2.0+), but since all those versions are obsolete I'm not going to test them.
> Fix MW 1.31 regression

- resources/styles/_extensionfixes.scss
MW 1.31 Echo styling was different compared to 1.35. This applies the 1.35 fix to 1.31.
> Improve Echo icon styling for MW 1.31

- docs/components.md
- docs/release-notes.md
- layouts/clean.xml
- layouts/fixedhead.xml
- layouts/layout.rng
- layouts/navhead.xml
- layouts/standard.xml
- layouts/stickyhead.xml
- maintenance/validateLayout.php
- src/Components/NavbarHorizontal/PersonalTools.php
Add `PersonalTools` attribute to allow showing the logged in user's real name or username next to the dropdown.
User with real name:
User without real name:
Default behavior:
> Add PersonalTools user name display

- skin.json
TOC styling was broken in 1.37.
Before:
After:
This does not affect MW 1.35's styling.
> Add TOC feature for MW 1.37

- layouts/layout.rng
- src/Components/Grid.php
I think the container or container-fluid class should be added before calling the parent constructor to allow explicitly defined classes in the layout to override the container class (e.g. with something like container-md).
> Update Grid.php to support container size with mode attribute

- docs/release-notes.md
- resources/styles/_functions.scss
- resources/styles/_mixins.scss
Chameleon previously defined an `abs()` function which overwrites the SASS core `abs()` (https://sass-lang.com/documentation/modules/math#abs).
This caused a compilation issue with Bootstrap 4.6.1 because it expected to use the core `abs()`:
https://github.com/ProfessionalWiki/Bootstrap/blob/524415029465d560e78e29eb50e2cdd0a8e25ea3/resources/bootstrap/scss/vendor/_rfs.scss#L54-L55
> Fix abs() issue with Bootstrap 4.6.1

- resources/styles/_fixes.scss
This one-liner in _fixes.scss adds a "nowrap" to nav-link elements, to prevent weird linebreaks from showing up if a navbar link contains whitespace, fattening the navbar and throwing off vertical alignment.
(Bootstrap already applies nowrap to dropdown-items.)
> Bootstrap tweak to prevent ugly linebreaks within navbar links

- docs/components.md
- docs/release-notes.md
- layouts/layout.rng
- src/Components/NavbarHorizontal/PersonalTools.php
This adds a `username-only` option to the `showUserName` attribute in the `PersonalTools` component (when used within the `NavbarHorizontal`), to show *only* the username for logged-in users.  The prior `yes` option has been renamed to `try-realname` for clarity, and the `no` option has been renamed to `none` (the new default).
For backwards compatibility, `no` and `yes` are still accepted, but a deprecation note has been added to the code.
> Add option to display username-only in PersonalTools (fixes #343)

- src/Components/NavMenu.php
This adds section-specific classes to the links/toggles created by `NavMenu`, following the model of `Toolbox`.  This allows for more CSS customizations, e.g., adding icons to NavMenu dropdown-toggles in the navbar.
For a section with `menuid` as its id:
- The wrapper `<div>` gets additional class `menuid-dropdown`.
- The toggle button `<a>` gets additional class `menuid-toggle`.
The existing code already assigns class `menuid` to the `<div>` containing the menu items (for sections that have a non-empty list of items).  This behavior has not been changed.
For example, the `navigation` section has id `p-navigation`, so:
- its wrapper `<div>` now gets class `p-navigation-dropdown`;
- the toggle button now gets class `p-navigation-toggle`;
- the menu already/still has class `p-navigation`.
> Add classes to NavMenu elements based on section/menu-id

- src/Components/NavbarHorizontal/Toolbox.php
This commit adds the machinery for providing a `title` attribute to the dropdown toggle `<a>` element of the `Toolbox` menu.  Following the usual MediaWiki scheme for tooltips, the `title` attribute will be populated with the contents of `MediaWiki:Tooltip-p-tb` (if that page has been created on the wiki).
> Provide a 'title' attribute to Toolbox's dropdown-toggle button

- src/Components/NavMenu.php
Currently, the `title` attribute on a NavMenu section/item is placed on the top-level wrapper `<div>` element, instead of the dropdown-toggle's `<a>` element.  Everywhere else, `title` attributes are placed directly on the `<a>` element of the button/item/link.
Since the top-level wrapper `<div>` encompasses the menu as well as the toggle, any items in the menu that do not have their own explicit `title` attribute will inherit the top-level title.  In other words, menu items that should not have tooltips will get the same tooltip as the dropdown-toggle.
This commit moves the `title` attribute in NavMenu off the top-level `<div>` and onto the toggle `<a>` element.
> Move 'title' attribute of NavMenu toggles to the <a> elements

- tests/phpunit/Unit/Components/FooterIconsTest.php
- tests/phpunit/Unit/Components/FooterInfoTest.php
- tests/phpunit/Unit/Components/FooterPlacesTest.php
- tests/phpunit/Unit/Hooks/SetupAfterCacheTest.php
To fix the test warnings caused by PHPUnit 9 + MW master: https://github.com/ProfessionalWiki/chameleon/actions/runs/3326977881/jobs/5501254610
> Replace deprecated test method

- resources/styles/_fixes.scss
In other words:
* When navbar items are laid out horizontally (wide browser window), align them so they are vertically centered.
* When navbar items are laid out vertically (collapsible panel), align them so they are horizontally centered.
> Tweak CSS to center-align navbar items in minor-axis direction

- resources/styles/Components/NavbarHorizontal.scss
It is not clear what the `.flex-row` on `.navbar-nav.right` elements was intended to accomplish, but the effect that it has is that, when the navbar is collapsed and switches to a vertical layout, all the right-grouped navbar items are jammed together into a single row (instead of switching to a vertical/column layout like the non-right- -grouped items).  Removing the `.flex-row` fixes that.
This commit also removes the `.justify-content-center`, which does not seem to have any effect at all on any layout/orientation/screen. (Since the `.navbar-nav.right` wrapper is always squeezed to the right, there is no free space into which its children can be centered.)
For what it's worth, this commit does leave the `.mt-4` in place; it does not seem to have any effect in the horizontal layout, and …
> Tweak CSS to fix grouping of "right" items when navbar is collapsed

- src/Components/NavbarHorizontal/PersonalTools.php
This commit adds a `ChameleonNavbarHorizontalPersonalToolsLinkInnerHtml` hook which can be used to completely customize the inner html of the dropdown toggle link of `PersonalTools`.
This hook will be passed three parameters:
* `$newtalkNotifierHtml` (by reference)
* `$userNameHtml` (by reference)
* the `PersonalTools` object
The first two parameters are strings bearing the values computed by the PersonalTools component (according to its configuration, etc), which the hook function may modify (or leave alone).
After the hook function is complete, the values of `$newtalkNotifierHtml` and `$userNameHtml` will be concatenated (in that order) to yield the raw html content of the dropdown toggle's `<a>` element.
> Add a hook for customizing the PersonalTools toggle <a> inner html

- docs/components.md
- layouts/layout.rng
- src/Components/NavbarHorizontal/PersonalTools.php
This commit adds a `promoteLoneItems` parameter to the `PersonalTools` component.  If there is only one personal tool, and its name is in the parameter, then the link for that tool will be rendered directly in the navbar (instead of in a dropdown menu).
A prime use of this parameter is for a semi-private wiki, where a logged-out user only has the `login` tool available.  With this parameter, the login button can be directly rendered (and thus, clicked) in the navbar, instead of being hidden in a menu activated by a dropdown toggle.
> Add option to PersonalTools to show lone menu items directly in navbar

- docs/components.md
- layouts/layout.rng
- src/Components/NavMenu.php
This commit adds new `include` and `exclude` attributes to the `NavMenu` component.  Both are intended to hold semicolon-separated lists of menu section names.  If neither is specified, the behavior is unchanged from the current behavior.  If `include` is provided, only the specified sections from the sidebar are processed.  If `exclude` is provided, the specified sections are skipped.
These options are complementary, and allow one to locate different menu sections in different `NavMenu` instances, e.g., in different locations on the page.
> Add options to NavMenu to include/exclude specific sections.

- docs/components.md
- docs/release-notes.md
- layouts/clean.xml
- layouts/fixedhead.xml
- layouts/layout.rng
- layouts/navhead.xml
- layouts/standard.xml
- layouts/stickyhead.xml
- maintenance/validateLayout.php
- src/Components/NavMenu.php
Fixes https://github.com/ProfessionalWiki/chameleon/issues/399
> Add showActive parameter

- resources/js/Components/toc.js
- resources/styles/Components/Toc.scss
- src/Components/Toc.php
Refs https://github.com/ProfessionalWiki/chameleon/issues/390
This collapses the H2 headings in the TOC component and adds collapse/expand buttons similar to the TOC in the Vector 2022 skin:
https://github.com/ProfessionalWiki/chameleon/assets/1428594/738ab5eb-b2dd-41d2-b341-44059a61f36e
TODOs:
* Documentation follow-up
* Tests (since this is based on regexing the TOC HTML)]
* Code can likely do with some cleanup
This PR should be squashed.
> Collapse H2 headings in TOC component

- .github/workflows/ci.yml
- composer.json
- docs/release-notes.md
* Raised minimum MediaWiki version from 1.35 to 1.39
* Raised minimum PHP version from 7.4.3 to 8.0
> Bump minimum requirements

- resources/styles/Components/Toc.scss
Improve the styles for the newly added Toc component, which adds a sticky table of contents:
- Restore a background color for the table.
- With that background color, the table shouldn't take up the entire width of the page, so remove the 100% width.
- Specify `z-index: 1;` for the wrapping div so that reference tooltips from the Cite extension are not shown through the table of contents.
- Restore the ability to toggle the visibility of the table of contents.
WE-279
> Toc component: style improvements

- src/Hooks/SetupAfterCache.php
Removed one line which was generating an error in the Javascript console:
> Special:Version:200 This page is using the deprecated ResourceLoader module "mediawiki.ui.button".
> [1.41] Please use Codex. See migration guidelines: https://w.wiki/7TAh
Unless I am missing something, mediawiki.ui.button is not used by current version of chameleon skin in any case. 
This edit removes it from the ResourceLoader.
> Remove 'mediawiki.ui.button' from ResourceLoader
